In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
#print(iris.DESCR)

In [6]:
X = iris.data

In [9]:
y = iris.target

In [11]:
from keras.utils import to_categorical

In [12]:
y = to_categorical(y)

In [13]:
y.shape

(150, 3)

In [14]:
#y

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler_object = MinMaxScaler()

In [19]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
scaled_X_train = scaler_object.transform(X_train)

In [21]:
scaled_X_test = scaler_object.transform(X_test)

In [22]:
# scaled_X_train

In [32]:
from keras.models import Sequential

In [33]:
from keras.layers import Dense

In [34]:
model = Sequential()

In [35]:
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 2s - loss: 1.1028 - accuracy: 0.3400
Epoch 2/150
 - 0s - loss: 1.0974 - accuracy: 0.3400
Epoch 3/150
 - 0s - loss: 1.0916 - accuracy: 0.3400
Epoch 4/150
 - 0s - loss: 1.0856 - accuracy: 0.3400
Epoch 5/150
 - 0s - loss: 1.0798 - accuracy: 0.3400
Epoch 6/150
 - 0s - loss: 1.0743 - accuracy: 0.3400
Epoch 7/150
 - 0s - loss: 1.0693 - accuracy: 0.3400
Epoch 8/150
 - 0s - loss: 1.0646 - accuracy: 0.3400
Epoch 9/150
 - 0s - loss: 1.0605 - accuracy: 0.3400
Epoch 10/150
 - 0s - loss: 1.0566 - accuracy: 0.3400
Epoch 11/150
 - 0s - loss: 1.0528 - accuracy: 0.3400
Epoch 12/150
 - 0s - loss: 1.0489 - accuracy: 0.3400
Epoch 13/150
 - 0s - loss: 1.0451 - accuracy: 0.3400
Epoch 14/150
 - 0s - loss: 1.0417 - accuracy: 0.3400
Epoch 15/150
 - 0s - loss: 1.0376 - accuracy: 0.3500
Epoch 16/150
 - 0s - loss: 1.0344 - accuracy: 0.3500
Epoch 17/150
 - 0s - loss: 1.0307 - accuracy: 0.3500
Epoch 18/150
 - 0s - loss: 1.0274 - accuracy: 0.3400
Epoch 1

Epoch 150/150
 - 0s - loss: 0.3850 - accuracy: 0.9200


In [38]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 1, 2])

In [39]:
predictions = model.predict_classes(scaled_X_test)

In [40]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [41]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [42]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 12,  3],
       [ 0,  0, 16]])

In [43]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.80      0.89        15
           2       0.84      1.00      0.91        16

   micro avg       0.94      0.94      0.94        50
   macro avg       0.95      0.93      0.93        50
weighted avg       0.95      0.94      0.94        50



In [44]:
accuracy_score(y_test.argmax(axis=1), predictions)

0.94

In [45]:
model.save('myfirstmodel.h5')

In [46]:
from keras.models import load_model

In [47]:
new_model = load_model('myfirstmodel.h5')

In [48]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 1, 2])